apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kube-xray.fullname" . }}
  labels:
    app: {{ template "kube-xray.name" . }}
    chart: {{ template "kube-xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.yaml: |-
    unscanned:
      deployments: {{ .Values.scanPolicy.unscanned.deployments | default "ignore" }}
      statefulSets: {{ .Values.scanPolicy.unscanned.statefulSets | default "ignore" }}
      whiltelistNamespaces: {{ .Values.scanPolicy.unscanned.whiltelistNamespaces | default "kube-system,kube-xray" }} 
    security:
      deployments: {{ .Values.scanPolicy.security.deployments | default "ignore" }}
      statefulSets: {{ .Values.scanPolicy.security.statefulSets | default "ignore" }}
    license:
      deployments: {{ .Values.scanPolicy.license.deployments | default "ignore"  }}
      statefulSets: {{ .Values.scanPolicy.license.statefulSets | default "ignore" }}
